export const hotelsData = {
  hotels: [
    {
      id: 0,
      name: 'Euro Hotel Wembley',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et feugiat lorem, eu tincidunt enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 100, double: 150, twin: 200 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 1,
      name: 'Olympia Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'false',
      price: { single: 101, double: 151, twin: 201 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 2,
      name: 'Kensington Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '2',
      hasPool: 'true',
      price: { single: 102, double: 152, twin: 202 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 3,
      name: 'Palace Court Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'false',
      price: { single: 103, double: 153, twin: 203 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 4,
      name: 'Travelodge Excel Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'false',
      price: { single: 104, double: 154, twin: 204 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 5,
      name: 'Euro Hotel Croydon',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et feugiat lorem, eu tincidunt enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 100, double: 150, twin: 200 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'false',
    },
    {
      id: 6,
      name: 'Royal Olympia Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'false',
      price: { single: 101, double: 151, twin: 201 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 7,
      name: 'Winchester Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '2',
      hasPool: 'true',
      price: { single: 102, double: 152, twin: 202 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 8,
      name: 'Newbury Court Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 103, double: 153, twin: 203 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 9,
      name: 'Travelodge Enfield Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'true',
      price: { single: 104, double: 154, twin: 204 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'true',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 10,
      name: 'Euro Hotel Chelsea',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et feugiat lorem, eu tincidunt enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '2',
      hasPool: 'false',
      price: { single: 100, double: 150, twin: 200 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 11,
      name: 'Aylesbury Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'true',
      price: { single: 101, double: 151, twin: 201 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 12,
      name: 'Dartford Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '2',
      hasPool: 'false',
      price: { single: 102, double: 152, twin: 202 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 13,
      name: 'Whitechurch Court Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 103, double: 153, twin: 203 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 14,
      name: 'Travelodge Hayes Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'true',
      price: { single: 104, double: 154, twin: 204 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 15,
      name: 'Euro Hotel Farnham',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et feugiat lorem, eu tincidunt enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'false',
      price: { single: 100, double: 150, twin: 200 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 16,
      name: 'Olympian Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'true',
      price: { single: 101, double: 151, twin: 201 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'false',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'false',
    },
    {
      id: 17,
      name: 'Oxford Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'false',
      price: { single: 102, double: 152, twin: 202 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 18,
      name: 'Broadchurch Court Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 103, double: 153, twin: 203 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'false',
    },
    {
      id: 19,
      name: 'Travelodge Windsor Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'true',
      price: { single: 104, double: 154, twin: 204 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 20,
      name: 'Euro Hotel Harrow',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et feugiat lorem, eu tincidunt enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      hasPool: 'true',
      price: { single: 100, double: 150, twin: 200 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'true',
    },
    {
      id: 21,
      name: 'Slough Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'true',
      price: { single: 101, double: 151, twin: 201 },
      hasFreeBreakfast: 'false',
      hasFreeParking: 'true',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
    {
      id: 22,
      name: 'Epson Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '5',
      hasPool: 'false',
      price: { single: 102, double: 152, twin: 202 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'false',
    },
    {
      id: 23,
      name: 'Chilton Court Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Nam eu sem feugiat, ultrices sem vitae, iaculis urna. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse vitae viverra ipsum.',
      rate: '3',
      price: { single: 103, double: 153, twin: 203 },
      hasPool: 'true',
      hasFreeBreakfast: 'true',
      hasFreeParking: 'false',
      hasFreeInternet: 'true',
      hasFreeCancellation: 'true',
      hasFreeShuttle: 'false',
    },
    {
      id: 24,
      name: 'Travelodge Ascot Hotel',
      img: 'https://source.unsplash.com/250x200/?hotel',
      address: '84 harken rd, London, England',
      location: { lat: '32.670295', lon: '35.107254' },
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris mi, rhoncus nec luctus eget, elementum sed sapien.',
      rate: '4',
      hasPool: 'false',
      price: { single: 104, double: 154, twin: 204 },
      hasFreeBreakfast: 'true',
      hasFreeParking: 'true',
      hasFreeInternet: 'false',
      hasFreeCancellation: 'false',
      hasFreeShuttle: 'true',
    },
  ],
};
